name: Test Code Generation

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test go
        run: go test -race -coverprofile=coverage.out -covermode=atomic -v ./...

      - name: Test coverage
        run: go tool cover -func coverage.out

      - name: Test code generation
        run: |
          go get -v ./...
          go generate ./pkg/codegen/templates
          go generate ./...
          go mod tidy
          git --no-pager diff && [[ 0 -eq $(git status --porcelain | wc -l) ]]
